language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "UScPApJId0aAQ5EupB2LtyoLMhioI1l9lmWZ5wEvkhSRseif+GVy+skTClQhpCArIbQFh5hCHsdG+kLZR4SqsnXI/j5sKLQA2vHlojY6rRTMAk6EnFk4xi+AwH42ytFt9q6P0yL6+ZKZwtg5v2b5IHXbYzf00Obfq/sQBd9rp/UwW6JTJNl9QyALGv7ka4irGnZVhUYw9KdUIIr1Oww6JUPckfO1p5xO7BUZpnQv+V3xDg8g9sALleyXrKRSex5/DlXhKuiy4fT/NadSZ+PkRRGBbOr/WSuAQgl+ScjKTId4DX1JqfhkfznIV2B/sweffwS66Q1ZvGFL3CREssTFa5rdQHFdD8xP8QW/Wyjmc77vM5ph3RXhJuPUCOZ+vJBo33tKzDkL58N0nIMvosng7kW8ZQBBIXTmqbj9FmbUTcibWg0gfgkwvNFnJl+Qahzx0NePqBkmTY5k+emI0Iygd1OAf9awrxNEka33B5gPO2SiTntREbHBIhehavfnfwC6FVup9mMNz9fdtjmYjeNNy7Z/KwA9YCmVsC4CjH9wXPQnCnywP45SY8nXIjUK0Oi1RTrhc4qfHjTgG30a41rNTxbbxmDwzTSWhSgqqACGXNhXWtTv58+yE7JPtwSbk2dyMSi6GplmX5R/0azpvy1UUZD4sGKKNmsXYFPPGRVlNmA="
  api_key: # 97d4
    secure: "YH0/6T8ROSwwcu76S2ujxGRijT7tIYzFmajSVkrcF+SX8Km1BhLppyu9paZERFr6Wwx8QIGBwcRglo2akqZuwJd/ImY34YwqDDQyGGpJh8QRSN/+2VaoeLbz+gIF8SxP8+xkQwIHcmJZySoeYqqkVL3Zp9F+RwWlh4gaKKoqSWhNQskoKQWdZ3YbGEe39vz2tI810tr+Gfv0sEfiv2X1sHgmBZgi/1sMK/ZaaWxaEDB22oqB3dOq/rKi/4y/MFvdlfifEbZa7poov+9ADY5FoVBr7NtcejNIKV45CYHKw9ihYIFwe7Wz5KRGKaM5NlStT/WUcdSaMOHMrT2u9pYvgZqyl5WriAyLNhM5LJ1ImNbVGAAypalb4TujE80eDX5EmWRNFqfaHhwOx4e5m1lih7wgvfF6j8VJuLTv1oayf/jE37c09dzE1vV2R9GSbQdqm5dQu06PlZW1FJf+K6p15V5B+MXmkXr409zexFt2mJPRRslw6h0QtP7bDxRRvFHT9BcErIZ06rAF1S47GeJFCPrEtJKHLoSizFiO3x9966ysXCBXbmwQrPLpdl3RbNYd2C1zB5cU22NwSfZAdzT/gK5u2IT4+UcbQg+CkwmVTB8vmjsT64CHrHwZND6ILWQZbAZM/OT60geR6Bw/OJaX88OwI2aPdiVNu9BCHdE3yC8="
  on:
    tags: true
    node: lts/*
